import { useRoute } from "wouter";
import { useSharedReport } from "@/hooks/use-scans";
import { ScanResultCard } from "@/components/ScanResultCard";
import { Activity, Loader2, AlertTriangle } from "lucide-react";

export default function SharedReport() {
  const [, params] = useRoute("/shared/:token");
  const token = params?.token || null;
  const { data, isLoading, isError } = useSharedReport(token);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-center space-y-3">
          <Loader2 className="w-10 h-10 animate-spin text-blue-500 mx-auto" />
          <p className="text-slate-500 font-medium">Loading shared report...</p>
        </div>
      </div>
    );
  }

  if (isError || !data?.scan) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6">
        <div className="max-w-md text-center space-y-3">
          <AlertTriangle className="w-12 h-12 text-amber-400 mx-auto" />
          <h1 className="text-xl font-bold text-slate-900">Report Not Found</h1>
          <p className="text-slate-500 text-sm">This shared link may be invalid or expired.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 pb-12">
      {/* Minimal header for shared view */}
      <div className="bg-white border-b border-slate-100 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-blue-600 to-teal-400 flex items-center justify-center text-white">
            <Activity className="w-5 h-5" />
          </div>
          <span className="font-display font-bold text-lg text-slate-900">SkinVision <sup className="text-[10px] font-semibold text-teal-500">PRO</sup></span>
          <span className="ml-auto text-xs bg-blue-50 text-blue-600 px-3 py-1 rounded-full font-semibold">Shared Report</span>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-6 pt-6">
        {data.consultation?.message && (
          <div className="bg-blue-50 rounded-xl p-4 border border-blue-100 mb-4">
            <p className="text-xs font-semibold text-blue-700 mb-1">Patient Message:</p>
            <p className="text-sm text-blue-800">{data.consultation.message}</p>
          </div>
        )}
        <ScanResultCard scan={data.scan} />
        <div className="mt-6 text-center">
          <p className="text-xs text-slate-400">This report was generated by SkinVision PRO AI analysis. It does not replace professional medical diagnosis.</p>
        </div>
      </div>
    </div>
  );
}
